# Data Science

In [1]:
import numpy as np

In [2]:
# seed is use to generate same random arrays each time its run
np.random.seed(0)

In [23]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [6]:
print("x3 ndim:\t", x3.ndim)
print("x3 shape:\t", x3.shape)
print("x3 size:\t", x3.size)
print("x3 dtype:\t", x3.dtype)

x3 ndim:	 3
x3 shape:	 (3, 4, 5)
x3 size:	 60
x3 dtype:	 int64


In [7]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Array indexing

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[0]

5

In [11]:
x1[-1]

9

In [14]:
x1[:-2]

array([5, 0, 3, 3])

In [15]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x2[0, 0]

3

In [17]:
x2[1:,2:]

array([[8, 8],
       [7, 7]])

In [20]:
x2[:-1, :-2]

array([[3, 5],
       [7, 6]])

In [24]:
x1[0] = 3.14159 #this will be truncated!

In [25]:
x1

array([3, 3, 4, 4, 8, 4])

## Reshaping

In [26]:
grid = np.arange(1, 10)

In [27]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
grid.shape

(9,)

In [29]:
grid = grid.reshape(3, 3)

In [30]:
grid.shape

(3, 3)

In [31]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])